# Generated by Django 2.2.5 on 2019-11-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20191123_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
