# Generated by Django 2.2.5 on 2019-11-26 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_auto_20191123_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_cliente', to='pessoas.Endereco'),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_entregador', to='pessoas.Endereco'),
        ),
    ]
