# Generated by Django 2.2.5 on 2019-11-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_auto_20191125_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='entregas',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
