# Generated by Django 2.2.5 on 2019-11-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_entregador_entregas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregador',
            name='entregas',
        ),
    ]
