# Generated by Django 2.2.5 on 2019-09-09 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BebidaTamanhoBebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyzza.Bebida')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyzza.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='FormaDePagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('qt_estoque', models.IntegerField()),
                ('qt_minima', models.IntegerField()),
                ('qt_maxima', models.IntegerField()),
                ('un_medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SaborBorda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='SaborPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoBebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(default='')),
                ('max_sabores', models.IntegerField(default=1)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('multiplicador', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='SaborPizzaIngredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.Ingrediente')),
                ('sabor_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyzza.SaborPizza')),
            ],
        ),
        migrations.AddField(
            model_name='saborpizza',
            name='tipo_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.TipoPizza'),
        ),
        migrations.CreateModel(
            name='SaborBordaIngredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.Ingrediente')),
                ('sabor_borda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyzza.SaborBorda')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('troco_para', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.Cliente')),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.Entregador')),
                ('forma_de_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.FormaDePagamento')),
                ('status_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.StatusPedido')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('observacao', models.TextField(default='')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyzza.Pedido')),
                ('sabor_borda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.SaborBorda')),
                ('sabores', models.ManyToManyField(to='pyzza.SaborPizza')),
                ('tamanho_pizza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.TamanhoPizza')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bebida_tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.BebidaTamanhoBebida')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyzza.Pedido')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyzza.Endereco'),
        ),
        migrations.AddField(
            model_name='bebidatamanhobebida',
            name='tamanho_bebida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyzza.TamanhoBebida'),
        ),
    ]
