# Generated by Django 2.2.5 on 2019-10-24 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyzza', '0001_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BebidaTamanhoBebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='pyzza.Bebida')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='pyzza.Endereco')),
            ],
            options={
                'verbose_name': 'Entregador',
                'verbose_name_plural': 'Entregadores',
            },
        ),
        migrations.CreateModel(
            name='FormaDePagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('qt_estoque', models.IntegerField()),
                ('qt_minima', models.IntegerField()),
                ('qt_maxima', models.IntegerField()),
                ('un_medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SaborBorda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sabor da Borda',
                'verbose_name_plural': 'Sabores de Bordas',
            },
        ),
        migrations.CreateModel(
            name='SaborPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(default='')),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='sabor_pizza_img/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Sabor de Pizza',
                'verbose_name_plural': 'Sabores de Pizzas',
            },
        ),
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Status do Pedido',
                'verbose_name_plural': 'Status de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='TamanhoBebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tamanho da Bebida',
                'verbose_name_plural': 'Tamanhos de Bebidas',
            },
        ),
        migrations.CreateModel(
            name='TamanhoPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('max_sabores', models.IntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('multiplicador', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Tamanho da Pizza',
                'verbose_name_plural': 'Tamanhos de Pizzas',
            },
        ),
        migrations.CreateModel(
            name='TipoPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Tipo de Pizza',
                'verbose_name_plural': 'Tipos de Pizzas',
            },
        ),
        migrations.CreateModel(
            name='SaborPizzaIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sabores_pizza', to='pyzza.Ingrediente')),
                ('sabor_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='pyzza.SaborPizza')),
            ],
            options={
                'verbose_name': 'Ingrediente do Sabor de Pizza',
                'verbose_name_plural': 'Ingredientes do Sabor de Pizza',
            },
        ),
        migrations.AddField(
            model_name='saborpizza',
            name='tipo_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.TipoPizza'),
        ),
        migrations.CreateModel(
            name='SaborBordaIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sabores_borda', to='pyzza.Ingrediente')),
                ('sabor_borda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='pyzza.SaborBorda')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('troco_para', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.Cliente')),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.Entregador')),
                ('forma_de_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.FormaDePagamento')),
                ('status_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.StatusPedido')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('observacao', models.TextField(blank=True, default='', null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyzza.Pedido')),
                ('sabor_borda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.SaborBorda')),
                ('sabores', models.ManyToManyField(to='pyzza.SaborPizza')),
                ('tamanho_pizza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.TamanhoPizza')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bebida_tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyzza.BebidaTamanhoBebida')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyzza.Pedido')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyzza.Endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bebidatamanhobebida',
            name='tamanho_bebida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bebidas', to='pyzza.TamanhoBebida'),
        ),
    ]
