# Generated by Django 2.2.5 on 2019-09-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyzza', '0004_auto_20190918_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregador',
            options={'verbose_name': 'Entregador', 'verbose_name_plural': 'Entregadores'},
        ),
        migrations.AlterModelOptions(
            name='formadepagamento',
            options={'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='saborborda',
            options={'verbose_name': 'Sabor da Borda', 'verbose_name_plural': 'Sabores de Bordas'},
        ),
        migrations.AlterModelOptions(
            name='saborpizza',
            options={'verbose_name': 'Sabor de Pizza', 'verbose_name_plural': 'Sabores de Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='saborpizzaingrediente',
            options={'verbose_name': 'Ingrediente do Sabor de Pizza', 'verbose_name_plural': 'Ingredientes do Sabor de Pizza'},
        ),
        migrations.AlterModelOptions(
            name='statuspedido',
            options={'verbose_name': 'Status do Pedido', 'verbose_name_plural': 'Status de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='tamanhobebida',
            options={'verbose_name': 'Tamanho da Bebida', 'verbose_name_plural': 'Tamanhos de Bebidas'},
        ),
        migrations.AlterModelOptions(
            name='tamanhopizza',
            options={'verbose_name': 'Tamanho da Pizza', 'verbose_name_plural': 'Tamanhos de Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='tipopizza',
            options={'verbose_name': 'Tipo de Pizza', 'verbose_name_plural': 'Tipos de Pizzas'},
        ),
        migrations.AlterField(
            model_name='formadepagamento',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='statuspedido',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
