# Generated by Django 2.2.5 on 2019-09-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyzza', '0005_auto_20190918_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='pyzza.Endereco'),
        ),
    ]
