# Generated by Django 2.2.5 on 2019-09-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyzza', '0006_auto_20190923_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(editable=False),
        ),
    ]
