# Generated by Django 2.2.5 on 2019-09-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyzza', '0007_auto_20190923_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
