# Generated by Django 2.2.5 on 2019-09-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyzza', '0008_auto_20190923_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='saborbordaingrediente',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
