# Generated by Django 2.2.5 on 2019-09-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyzza', '0009_saborbordaingrediente_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saborbordaingrediente',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='saborborda',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saborborda',
            name='ingredientes',
            field=models.ManyToManyField(related_name='ingredientes', to='pyzza.Ingrediente'),
        ),
    ]
