# Generated by Django 2.2.5 on 2019-09-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyzza', '0010_auto_20190925_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saborborda',
            name='ingredientes',
        ),
    ]
