# Generated by Django 2.2.5 on 2019-09-26 00:53

from django.db import migrations
from django.contrib.auth.admin import User

def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'admin'
    superuser.email = 'admin@admin.net'
    superuser.set_password('admin')
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pyzza', '0011_remove_saborborda_ingredientes'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]


