# Generated by Django 2.2.5 on 2019-10-20 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyzza', '0011_remove_saborborda_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='saborpizza',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saborpizza',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='sabor_pizza_img/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='itempizza',
            name='observacao',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='saborpizzaingrediente',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sabores', to='pyzza.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='saborpizzaingrediente',
            name='sabor_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='pyzza.SaborPizza'),
        ),
    ]
