# Generated by Django 2.2.6 on 2019-11-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20191111_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembebida',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_bebida', to='pedidos.Pedido'),
        ),
    ]
