# Generated by Django 2.2.5 on 2019-11-18 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20191113_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_de_pagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pedidos.FormaDePagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pedidos.StatusPedido'),
        ),
    ]
