# Generated by Django 2.2.5 on 2019-11-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20191118_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempizza',
            name='descontado_estoque',
            field=models.BooleanField(default=False),
        ),
    ]
