# Generated by Django 2.2.5 on 2019-12-01 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_itempizza_descontado_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descontado_estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='entregador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido', to='pessoas.Entregador'),
        ),
    ]
