# Generated by Django 2.2.6 on 2019-11-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('qt_estoque', models.IntegerField()),
                ('qt_minima', models.IntegerField()),
                ('qt_maxima', models.IntegerField()),
                ('un_medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SaborBorda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sabor da Borda',
                'verbose_name_plural': 'Sabores de Bordas',
            },
        ),
        migrations.CreateModel(
            name='SaborPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(default='')),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='sabor_pizza_img/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Sabor de Pizza',
                'verbose_name_plural': 'Sabores de Pizzas',
            },
        ),
        migrations.CreateModel(
            name='TamanhoPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('max_sabores', models.IntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('multiplicador', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Tamanho da Pizza',
                'verbose_name_plural': 'Tamanhos de Pizzas',
            },
        ),
        migrations.CreateModel(
            name='TipoPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Tipo de Pizza',
                'verbose_name_plural': 'Tipos de Pizzas',
            },
        ),
        migrations.CreateModel(
            name='SaborPizzaIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sabores_pizza', to='pizzas.Ingrediente')),
                ('sabor_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='pizzas.SaborPizza')),
            ],
            options={
                'verbose_name': 'Ingrediente do Sabor de Pizza',
                'verbose_name_plural': 'Ingredientes do Sabor de Pizza',
            },
        ),
        migrations.AddField(
            model_name='saborpizza',
            name='tipo_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzas.TipoPizza'),
        ),
        migrations.CreateModel(
            name='SaborBordaIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sabores_borda', to='pizzas.Ingrediente')),
                ('sabor_borda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='pizzas.SaborBorda')),
            ],
        ),
    ]
