# Generated by Django 2.2.5 on 2019-11-18 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20191118_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saborpizzaingrediente',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pivot', to='pizzas.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='saborpizzaingrediente',
            name='sabor_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivot', to='pizzas.SaborPizza'),
        ),
    ]
