# Generated by Django 2.2.5 on 2019-11-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20191118_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='qt_estoque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='qt_maxima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='qt_minima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='saborpizzaingrediente',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sabores_pivot', to='pizzas.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='saborpizzaingrediente',
            name='sabor_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_pivot', to='pizzas.SaborPizza'),
        ),
    ]
