# Generated by Django 2.2.5 on 2019-11-18 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20191118_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='saborborda',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='sabores_borda', through='pizzas.SaborBordaIngrediente', to='pizzas.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='saborbordaingrediente',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sabores_borda_pivot', to='pizzas.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='saborbordaingrediente',
            name='sabor_borda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_borda_pivot', to='pizzas.SaborBorda'),
        ),
    ]
