# Generated by Django 2.2.6 on 2019-11-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_tamanhopizza_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tamanhopizza',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Tamanho da Pizza', 'verbose_name_plural': 'Tamanhos de Pizzas'},
        ),
    ]
