# Generated by Django 2.2.5 on 2019-12-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0011_auto_20191125_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saborpizza',
            options={'ordering': ['tipo_pizza', 'nome'], 'verbose_name': 'Sabor de Pizza', 'verbose_name_plural': 'Sabores de Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='tipopizza',
            options={'ordering': ['ordem'], 'verbose_name': 'Tipo de Pizza', 'verbose_name_plural': 'Tipos de Pizzas'},
        ),
        migrations.AddField(
            model_name='tipopizza',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
