# Generated by Django 2.2.6 on 2019-11-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoBebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tamanho da Bebida',
                'verbose_name_plural': 'Tamanhos de Bebidas',
            },
        ),
        migrations.CreateModel(
            name='BebidaTamanhoBebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='bebidas.Bebida')),
                ('tamanho_bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bebidas', to='bebidas.TamanhoBebida')),
            ],
        ),
    ]
