# Generated by Django 2.2.5 on 2019-11-16 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='tamanhos',
            field=models.ManyToManyField(related_name='tamanhos', through='bebidas.BebidaTamanhoBebida', to='bebidas.TamanhoBebida'),
        ),
        migrations.AlterField(
            model_name='bebidatamanhobebida',
            name='bebida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebidas.Bebida'),
        ),
    ]
