# Generated by Django 2.2.5 on 2019-11-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0002_auto_20191115_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='tamanhos',
            field=models.ManyToManyField(related_name='bebidas', through='bebidas.BebidaTamanhoBebida', to='bebidas.TamanhoBebida'),
        ),
        migrations.AlterField(
            model_name='bebidatamanhobebida',
            name='tamanho_bebida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebidas.TamanhoBebida'),
        ),
    ]
