# Generated by Django 2.2.6 on 2019-11-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0003_auto_20191117_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebidatamanhobebida',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
