# Generated by Django 2.2.6 on 2019-11-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0004_bebidatamanhobebida_disponivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bebidatamanhobebida',
            options={'verbose_name': 'Opção de Bebida', 'verbose_name_plural': 'Opções de Bebida'},
        ),
    ]
