# Generated by Django 2.2.5 on 2019-11-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0005_auto_20191122_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tamanhobebida',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
