# Generated by Django 2.2.5 on 2019-12-01 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0006_auto_20191125_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bebida',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='tamanhobebida',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bebidatamanhobebida',
            name='bebida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='bebidas.Bebida'),
        ),
    ]
